pipeline {
    agent any

    stages {
        stage('Springboot build'){
            steps{
                dir('BE'){
                    sh '''
                    echo 'Springboot build...'
                    chmod +x gradlew
                    ./gradlew clean build
                    '''
                }
            }
        }

        stage('Dockerimage build'){
            steps{
                dir('BE'){
                    echo 'Dockerimage build...'
                    sh 'docker stop springboot'
                    sh 'docker rm springboot'
                    sh 'docker images -q docker-react | xargs docker rmi'
                    sh 'docker build -t docker-springboot:0.0.1 .'
                }
            }
        }

        stage('Deploy'){
            steps{
                dir('BE'){
                    sh '''
                    echo 'Deploy BE...'

                    docker run -d -p 8081:8080 --name springboot docker-springboot:0.0.1
                    '''
                }
            }
        }
    }
}